---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 4544544/spring-boot-mongo:latest
        ports:
        - containerPort: 8080
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: credentials
              key: token
